### ISSUE TITLE
a 1BTC payment asks for more on order screen

### ISSUE THREAD

**Issue by go6media** [Paybear/paybear-woocommerce#2]
The native currency for the woo install is set to BTC. I have a product which cost 1BTC. I process the order and get to the currency selection screen but the rate it is asking me to pay is 

1.04232627 BTC

how is that possible when the product costs 1BTC ?

commission? TX charge? surely isn't that much and definitely isn't clear

**Comment by go6media** [comment]
Done a second time and now its saying less!? see attached.

The order summary screen really should elaborate more as to what needs to be paid properly and the fees involved.

<img width="604" alt="screen shot 2018-02-25 at 10 33 02" src="https://user-images.githubusercontent.com/6851754/36640475-5e3e75fa-1a17-11e8-9706-5ee184678c0a.png">

**Comment by brunocrosier** [comment]
I'm in no way connected to PayBear but this is probably because your store's currency is set to BTC. So PayBear is now trying to convert from BTC to BTC but it's clearly bugging out. I would recommend changing your store's currency to USD for now and it will work fine.

**Comment by go6media** [comment]
Thanks for the comment but unfortunately, that's not a viable solution... my store is in the Bitcoin currency (a default currency selectable from the woo options) as such this plugin should be able to know and handle that accordingly.

**Comment by Paybear** [comment]
Could you please let us know what module/plugin did you use to change your store currency to BTC?
This is not something WooCommerce lets you do our of the box.

**Comment by go6media** [comment]
Using no plug ins other than Crypto Payments for WooCommerce by PayBear.io and woo... See screenshot

![image](https://user-images.githubusercontent.com/6851754/36734857-a3fabb56-1bcc-11e8-911d-50c546623974.png)

**Comment by Paybear** [comment]
Found it, thank you. Will be fixed in next release.

**Comment by go6media** [comment]
Also as a heads up - we are going to be using "All Currencies for WooCommerce" https://wordpress.org/plugins/woocommerce-all-currencies/ 

which allows us to activate ETH / LTC and some other alt coins - so please trial with these enabled too if possible
